#!/usr/bin/env node
'use strict';
/**
 * Vault capture suite: journals, project pages, dashboard, injection.
 * Everything runs in a temporary HOME and vault — never the real ones.
 *
 *   node test-vault.js
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const TMP = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'ccx-vt-')));
const HOME = path.join(TMP, 'home');
const VAULT = path.join(TMP, 'vault');
fs.mkdirSync(HOME, { recursive: true });
fs.mkdirSync(VAULT, { recursive: true });
Object.assign(process.env, { HOME, CC_VAULT: VAULT, CC_VAULT_DISABLED: '', CCX_DEBUG: '' });

const LIB = path.join(__dirname, 'hooks', 'lib');
const v = require(path.join(LIB, 'vault.js'));
const F = require(path.join(LIB, 'vault', 'filters.js'));
const C = require(path.join(LIB, 'vault', 'capture.js'));
const D = require(path.join(LIB, 'vault', 'dashboard.js'));
const { writeState, STATE_DIR } = require(path.join(LIB, 'util.js'));
const T = require('./tests/vault/transcript-builder');

let pass = 0, fail = 0;
const group = (name) => console.log(`\n  ${name}`);
function check(label, actual, expected) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  ok ? pass++ : fail++;
  console.log(`    ${ok ? 'OK  ' : 'FAIL'} ${label}${ok ? '' : `  (obtenu ${JSON.stringify(actual)}, attendu ${JSON.stringify(expected)})`}`);
}
const read = (f) => { try { return fs.readFileSync(f, 'utf8'); } catch { return ''; } };

// A fake project: git root with a github origin and a branch.
const PROJ = path.join(TMP, 'demo-project');
fs.mkdirSync(path.join(PROJ, '.git'), { recursive: true });
fs.writeFileSync(path.join(PROJ, '.git', 'HEAD'), 'ref: refs/heads/main\n');
fs.writeFileSync(path.join(PROJ, '.git', 'config'),
  '[core]\n\tbare = false\n[remote "origin"]\n\turl = git@github.com:octo-org/demo-project.git\n');

// ---------------------------------------------------------------- prompts
group('Demandes : seuls les vrais messages tapés');
[
  'Another Claude session sent a message: do X',
  '<agent-message from="a">hand-back</agent-message>',
  'Stop hook feedback:\n[Compagnons] demos.ts manquant',
  '[Request interrupted by user for tool use]',
  '<local-command-stdout>ok</local-command-stdout>',
  '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
  '<system-reminder>ctx</system-reminder>',
  '<task-notification>done</task-notification>',
  'Caveat: The messages below were generated by the user while running local commands.',
  `# Plan skill\n\n## When\n\n${'Long injected command body. '.repeat(20)}`,
].forEach((t) => check(`exclu : ${t.slice(0, 40).replace(/\n/g, ' ')}`, F.userPrompt(t), null));
check('vrai message conservé', F.userPrompt('ajoute un test pour le parseur'), 'ajoute un test pour le parseur');
check('commande avec arguments → /nom args', F.userPrompt('<command-message>plan</command-message>\n<command-name>/plan</command-name>\n<command-args>refonte du journal</command-args>'), '/plan refonte du journal');
const long = F.userPrompt('mot '.repeat(80));
check('coupé à ~200 car. sur un mot, avec …', [long.length <= 201, long.endsWith('mot…')], [true, true]);
const asksAcc = C.ingest(null, T.session([
  T.user('premier vrai message'), T.user('Expanded skill body', { isMeta: true }),
  T.user('premier vrai message'), T.user('second message'),
]), PROJ);
check('corps de slash-command (isMeta) exclu, doublons fusionnés', asksAcc.asks, ['premier vrai message', 'second message']);

// ---------------------------------------------------------------- result and excerpt
group('Résultat et extrait');
check('ligne result: extraite', F.headline('Intro.\n\n| a | b |\n|---|---|\n\nresult: 12 tests verts, journal refait'), '12 tests verts, journal refait');
check('failed: conservé comme préfixe', F.headline('Bla.\n**failed:** build rouge'), 'failed: build rouge');
check('sans ligne result : première phrase', F.headline('## Titre\n\nLe build passe. Reste la doc.'), 'Le build passe.');
const md = ['## Bilan', '', '| a | b |', '|---|---|', '| 1 | 2 |', '', '- point un', '- point deux'].join('\n');
check('extrait : sauts de ligne et Markdown préservés', F.excerpt(md), md);
const fenced = ['l1', 'l2', 'l3', '```js', 'a()', 'b()', 'c()', '```', 'fin'].join('\n');
const cut = F.excerpt(fenced, 5);
check('extrait coupé avant un bloc de code ouvert', cut, 'l1\nl2\nl3\n…');
const onlyFence = F.excerpt(['```', ...Array(30).fill('x'), '```'].join('\n'), 5);
check('bloc de code seul : refermé', [onlyFence.split('\n').filter((l) => l === '```').length, onlyFence.endsWith('…')], [2, true]);

// ---------------------------------------------------------------- files
group('Fichiers touchés : projet uniquement');
const filesAcc = C.ingest(null, T.session([
  T.edit('e1', path.join(PROJ, 'src', 'a.js')),
  T.edit('e2', path.join(PROJ, 'src', 'a.js')),
  T.edit('e3', path.join(PROJ, '.claude', 'worktrees', 'agent-1', 'src', 'b.js')),
  T.edit('e4', path.join(os.homedir(), '.claude', 'jobs', 'abc', 'tmp', 'wt', 'x.js')),
  T.edit('e5', '/tmp/scratch.md'),
  T.edit('e6', '/private/var/folders/zz/T/y.js'),
  T.edit('e7', '/srv/other-repo/z.js'),
]), PROJ);
check('chemins relatifs, dédoublonnés, worktree ramené', filesAcc.files, ['src/a.js', 'src/b.js']);
check('temporaires et autres dépôts comptés hors projet', filesAcc.outside.length, 4);
const rendered = require(path.join(LIB, 'vault', 'render.js')).renderSession(filesAcc, {});
check('titre avec compte hors projet', rendered.includes('> [!todo]- Fichiers touchés (2) (+4 hors projet)'), true);
check('aucun chemin absolu rendu', rendered.includes('/tmp/') || rendered.includes(os.homedir()), false);

// ---------------------------------------------------------------- errors
group('Erreurs : refus comptés, bruit écarté');
const errAcc = C.ingest(null, T.session([
  T.fail('b1', '[Fact-Forcing Gate] Avant ce Bash, cite la demande'),
  T.fail('b2', 'PreToolUse:Bash hook error: [Bloqué] force push'),
  T.fail('b3', 'Permission for this action was denied by the Claude Code auto mode classifier.'),
  T.fail('b4', '<tool_use_error>File has not been read yet. Read it first.</tool_use_error>'),
  T.fail('b5', 'Found 3 matches of the string'),
  T.fail('b6', 'Exit code 1\nnpm ERR! missing script: lint'),
  T.fail('b7', 'Exit code 1\nnpm ERR! missing script: lint\nmore'),
  T.fail('b8', 'x'.repeat(400)),
]), PROJ);
check('refus de garde-fous comptés', errAcc.refusals, 3);
check('bruit écarté, doublons fusionnés', errAcc.errors.length, 2);
check('ligne « exit N: » lisible', errAcc.errors[0], 'exit 1: npm ERR! missing script: lint');
check('chaque erreur ≤ 160 car.', errAcc.errors.every((e) => e.length <= 161), true);
const errBlock = require(path.join(LIB, 'vault', 'render.js')).renderSession(errAcc, {});
check('titre « Erreurs (2) · 3 refus de garde-fous »', errBlock.includes('> [!warning]- Erreurs (2) · 3 refus de garde-fous'), true);
check('aucun refus listé', /Fact-Forcing|Bloqué|classifier/.test(errBlock), false);

// ---------------------------------------------------------------- end to end
group('Journal : un bloc par session, mis à jour en place');
const J = path.join(VAULT, 'Claude', 'Journal');
const journalPath = () => path.join(J, fs.readdirSync(J).find((f) => f.endsWith('— demo-project.md')));
const tp1 = path.join(TMP, 's1.jsonl');
const s1 = T.fullSession(PROJ);
T.writeJsonl(tp1, s1);
const stopInput = (sid, tp) => ({ session_id: sid, transcript_path: tp, cwd: PROJ });
v.onStop(stopInput('sess-one', tp1));
check('aucune capture sans fichier édité (état edited vide)', fs.existsSync(J) ? fs.readdirSync(J).length : 0, 0);
writeState('sess-one', 'edited', [path.join(PROJ, 'src', 'a.js')]);
v.onStop(stopInput('sess-one', tp1));
let jr = read(journalPath());
check('bloc de session créé', (jr.match(/<!-- claude:session:sess-one:start -->/g) || []).length, 1);
check('tableau conservé dans l\'extrait', jr.includes('> | Étape | État |'), true);
T.appendJsonl(tp1, [T.user('et la doc ?'), T.text('Doc ajoutée.\n\nresult: doc à jour, 3 fichiers')], { branch: 'feat/journal' });
v.onStop(stopInput('sess-one', tp1));
jr = read(journalPath());
check('second Stop : toujours un seul bloc', (jr.match(/claude:session:sess-one:start/g) || []).length, 1);
check('bloc mis à jour (nouveau résultat)', jr.includes('> doc à jour, 3 fichiers'), true);
check('titre HH:MM–HH:MM — branche', /^## \d{2}:\d{2}–\d{2}:\d{2} — feat\/journal$/m.test(jr), true);
check('callouts natifs attendus', ['> [!summary] Résultat', '> [!question]- Demandé', '> [!info]- Commits et PR',
  '> [!todo]- Fichiers touchés', '> [!warning]- ', '> [!quote]- Dernier état'].every((c) => jr.includes(c)), true);
check('lien de commit depuis origin github', jr.includes('[abc1234](https://github.com/octo-org/demo-project/commit/abc1234def)'), true);
check('lien de PR', jr.includes('[PR #42](https://github.com/octo-org/demo-project/pull/42)'), true);
check('message d\'agent et commande sans arguments absents', /Another Claude|agent-message|\/clear/.test(jr), false);

const tp2 = path.join(TMP, 's2.jsonl');
T.writeJsonl(tp2, T.session([T.user('deuxième session'), T.edit('w1', path.join(PROJ, 'README.md')),
  T.text('result: seconde session close')]));
writeState('sess-two', 'edited', [path.join(PROJ, 'README.md')]);
v.onStop(stopInput('sess-two', tp2));
jr = read(journalPath());
check('nouvelle session → nouveau bloc', (jr.match(/claude:session:[\w-]+:start/g) || []).length, 2);

group('Frontmatter, page projet, tableau de bord');
const fm = jr.split('\n---\n')[0];
check('clés type/date/projet/tags/sessions/branches', ['type: session', 'date: ', 'projet: demo-project',
  'tags: [claude, session, demo-project]', 'sessions: 2', 'branches: [feat/journal, main]'].map((k) => fm.includes(k)), Array(6).fill(true));
const projPage = read(path.join(VAULT, 'Claude', 'Projets', 'demo-project.md'));
const entries = v.readRegion(projPage, 'journal').split('\n');
check('page projet : une entrée par session, dernière en tête', entries.length, 2);
check('entrée avec résultat', /^- \[\[\d{4}-\d{2}-\d{2} — demo-project\]\] — seconde session close$/.test(entries[0]), true);
const dash = read(D.DASHBOARD);
check('tableau de bord créé avec bloc géré', v.readRegion(dash, 'dashboard').includes('[[demo-project]] — doc à jour, 3 fichiers'), true);
check('sans statistiques : ligne neutre', dash.includes('**Compression des sorties (7 j)** : aucune commande enveloppée.'), true);
fs.mkdirSync(STATE_DIR, { recursive: true });
const now = new Date().toISOString();
fs.writeFileSync(D.STATS, [{ ts: now, before: 5000, after: 1000 }, { ts: now, before: 300, after: 300 },
  { ts: '2000-01-01T00:00:00Z', before: 9e6, after: 0 }].map((r) => JSON.stringify(r)).join('\n') + '\nnot json\n');
D.updateDashboard();
check('ligne de compression (7 j)', read(D.DASHBOARD).includes('2 commandes enveloppées, 1 compressées, 4 000 car. économisés (~1 000 tokens)'), true);

group('Injection au démarrage');
const inj = v.buildInjection(PROJ) || '';
check('aucun marqueur de callout injecté', /\[!\w+\]|^> /m.test(inj), false);
check('ni extrait ni fichiers injectés', /Dernier état|src\/a\.js|Fichiers touchés/.test(inj), false);
check('résultats récents injectés', inj.includes('seconde session close'), true);
const budgetInj = spawnSync('node', ['-e', 'process.stdout.write(require(process.argv[1]).buildInjection(process.argv[2]) || "")',
  path.join(LIB, 'vault.js'), PROJ], { encoding: 'utf8', env: { ...process.env, CC_VAULT_BUDGET_JOURNAL: '60' } }).stdout;
const jpart = budgetInj.split('### Dernière session\n')[1] || '';
check('budget journal respecté', jpart.replace('\n</contexte-vault>\n', '').length <= 60, true);

group('Migration : ancien format intact');
const legacyFile = path.join(J, '2020-01-01 — demo-project.md');
const legacy = '---\ntype: session\ndate: 2020-01-01\nprojet: demo-project\n---\n\n# 2020-01-01 — [[demo-project]]\n\n' +
  '## 10:00 — Fin de session\n\n**Demandé**\n- ancien\n\nNOTE HUMAINE\n';
fs.writeFileSync(legacyFile, legacy);
const tp3 = path.join(TMP, 's3.jsonl');
T.writeJsonl(tp3, T.session([T.user('reprise'), T.edit('m1', path.join(PROJ, 'x.js')), T.text('result: ok')]));
writeState('sess-three', 'edited', ['x']);
writeState('sess-three', 'vault', { ...C.emptyAcc(), journal: legacyFile });
v.onStop(stopInput('sess-three', tp3));
const mig = read(legacyFile);
check('ancien bloc et note humaine intacts', mig.includes('## 10:00 — Fin de session\n\n**Demandé**\n- ancien\n\nNOTE HUMAINE\n'), true);
check('nouveau bloc ajouté après, sessions: 2', [mig.includes('claude:session:sess-three:start'), /^sessions: 2$/m.test(mig)], [true, true]);

group('Robustesse et performance');
const hook = spawnSync('node', [path.join(__dirname, 'hooks', 'dispatch.js'), 'stop'], {
  input: JSON.stringify(stopInput('sess-one', '/nonexistent.jsonl')), encoding: 'utf8',
  env: { ...process.env, CCX_DEBUG: '1', CC_CONTEXT_MONITOR: 'off', CCX_DISABLED: '1' } });
check('transcript absent : sortie 0, aucune erreur interne', [hook.status, /\[ccx:/.test(hook.stderr)], [0, false]);
const big = path.join(TMP, 'big.jsonl');
T.writeLarge(big, 5 * 1024 * 1024, PROJ);
// Best of 3 runs, each on a fresh session: the other suites run in parallel, and
// one descheduled run must not fail a threshold the code actually meets.
const timed = (fn) => { const t0 = process.hrtime.bigint(); fn(); return Number(process.hrtime.bigint() - t0) / 1e6; };
const firstRuns = [], nextRuns = [];
for (let i = 1; i <= 3; i++) {
  const id = `sess-big-${i}`;
  writeState(id, 'edited', ['x']);
  firstRuns.push(timed(() => v.onStop(stopInput(id, big))));
  T.appendJsonl(big, [T.user('encore'), T.text('result: fini')]);
  nextRuns.push(timed(() => v.onStop(stopInput(id, big))));
}
const firstMs = Math.min(...firstRuns);
const nextMs = Math.min(...nextRuns);
console.log(`    --   transcript 5 Mo (meilleur de 3) : premier Stop ${firstMs.toFixed(1)} ms, Stop suivant ${nextMs.toFixed(1)} ms`);
check('premier Stop < 150 ms sur 5 Mo', firstMs < 150, true);
check('Stop incrémental < 30 ms', nextMs < 30, true);

fs.rmSync(TMP, { recursive: true, force: true });
console.log(`\n  vault : ${pass} réussis, ${fail} échoués sur ${pass + fail}\n`);
process.exit(fail ? 1 : 0);
